# Generated by Django 5.2.7 on 2025-10-08 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LearningPathEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learning.learningpath')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Learning Path Enrollment',
                'verbose_name_plural': 'Learning Path Enrollments',
                'unique_together': {('learning_path', 'user_profile')},
            },
        ),
        migrations.AddField(
            model_name='learningpath',
            name='assigned_profiles',
            field=models.ManyToManyField(blank=True, related_name='learning_paths', through='learning.LearningPathEnrollment', to='accounts.userprofile'),
        ),
        migrations.CreateModel(
            name='LearningPathStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='learning.learningpath')),
            ],
            options={
                'ordering': ('order', 'id'),
                'unique_together': {('learning_path', 'order')},
            },
        ),
        migrations.CreateModel(
            name='LearningPathProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='learning.learningpath')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='accounts.userprofile')),
                ('last_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='learning.learningpathstep')),
            ],
            options={
                'verbose_name': 'Learning Path Progress',
                'verbose_name_plural': 'Learning Path Progress Records',
                'unique_together': {('user_profile', 'learning_path')},
            },
        ),
        migrations.CreateModel(
            name='LearningPathStepBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=16)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='learning_path_blocks/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='learning.learningpathstep')),
            ],
            options={
                'ordering': ('order', 'id'),
                'unique_together': {('step', 'order')},
            },
        ),
        migrations.CreateModel(
            name='LearningPathStepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('unstarted', 'Unstarted'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='unstarted', max_length=20)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progress_entries', to='learning.learningpathprogress')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progress_records', to='learning.learningpathstep')),
            ],
            options={
                'ordering': ('step__order', 'id'),
                'unique_together': {('progress', 'step')},
            },
        ),
    ]
