# Generated by Django 5.2.7 on 2025-10-15 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_can_create_learning_paths_and_more'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_learning_paths', to='accounts.userprofile'),
        ),
    ]
